askMe/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^', include('askMe_app.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

askMe_app/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views 

app_name = 'askMe_app'
urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^(?P<page_num>[0-9]+)/$', views.index, name = 'index'),
	url(r'^hot/$', views.hot, name = 'hot'),
	url(r'^hot/(?P<page_num>[0-9]+)/$', views.hot, name = 'hot'),
	url(r'^tag/(?P<tag_name>[\S]+)/$', views.tag, name = 'tag'),
	url(r'^tag/(?P<tag_name>[\S]+)/(?P<page_num>[0-9]+)/$', views.tag, name = 'tag'),
	url(r'^question/(?P<question_id>[0-9]+)/$', views.question, name = 'question'),
	url(r'^question/(?P<question_id>[0-9]+)/(?P<page_num>[0-9]+)/$', views.question, name = 'question'),
	url(r'^ask/$', views.ask, name = 'ask'),
	url(r'^login/$', views.login_view, name = 'login'),
	url(r'^logout/$', views.logout_view, name = 'logout'),
	url(r'^signup/$', views.signup, name = 'signup'),
	url(r'^settings/$', views.settings, name = 'settings'),
	url(r'^like_question/$', views.like_question, name = 'like_question'),
	url(r'^like_answer/$', views.like_answer, name = 'like_answer'),
	url(r'^correct/$', views.correct_answer, name = 'correct'),
	url(r'^search/$', views.search, name = 'search'),
]

askMe_app/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import *
from django.core import validators

import re

from .models import *

class CommaSeparatedCharField(forms.Field):
	def __init__(self, *args, **kwargs):
		super(CommaSeparatedCharField, self).__init__(*args, **kwargs)

	def to_python(self, value):
		if value in validators.EMPTY_VALUES:
			return []

		value = [item.strip() for item in value.split(',') if item.strip()]

		return value

	def clean(self, value):
		value = self.to_python(value)
		self.validate(value)
		self.run_validators(value)
		return value


class AnswerForm(forms.Form):
	text = forms.CharField(widget = forms.Textarea(attrs = {
		'class': 'form-control input-lg', 
		'placeholder': 'Enter your answer here',
		'rows': 5,
		}))

	def save(self, question_id, user_id = 228):
		data = self.cleaned_data
		answer = Answer(text = data['text'], question_id = question_id, author_id = user_id)
		answer.save()


class AskForm(forms.Form):
	title = forms.CharField(widget = forms.TextInput(attrs = {
		'class': 'form-control input-lg',
		'placeholder': 'Enter the title here'
		}))
	text = forms.CharField(widget = forms.Textarea(attrs = {
		'class': 'form-control input-lg', 
		'placeholder': 'Enter your question here',
		'rows': 20,
		}))
	tags = CommaSeparatedCharField(required = False, widget = forms.TextInput(attrs = {
		'class': 'form-control input-lg',
		'placeholder': 'Enter the tags separated by comma'
		}))

	def clean_tags(self):
		tags = self.cleaned_data['tags']
		for t in tags:
			if re.search(r'\s', t):
				raise forms.ValidationError('One or more tags contains spaces')
		return tags

	def save(self, user_id):
		data = self.cleaned_data
		question = Question(title = data['title'], text = data['text'], author_id = user_id)
		question.save()
		tags = data['tags']
		for t in tags:
			tag = Tag.objects.tag_by_name(t)
			if tag is None:
				tag = Tag(name = t)
				tag.save()
			question.tags.add(tag)
		question.save()

		return question

class LoginForm(forms.Form):

	username = forms.CharField(widget = forms.TextInput(attrs = {
		'class': 'form-control input-lg',
		'placeholder': 'Enter your login here'
		}))
	password = forms.CharField(widget = forms.PasswordInput(attrs = {
		'class': 'form-control input-lg',
		'placeholder': 'Enter your password here'
		}))

	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']

		self.user = authenticate(username = username, password = password)

		if self.user is None:
			raise forms.ValidationError('Wrong login or password!')



class SignUpForm(forms.Form):

	username = forms.CharField(widget = forms.TextInput(attrs = {
		'class': 'form-control input-lg',
		'placeholder': 'Enter your login here'
		}))
	email = forms.EmailField(widget = forms.EmailInput(attrs = {
		'class': 'form-control input-lg',
		'placeholder': 'Enter your e-mail here'
		}))
	password = forms.CharField(widget = forms.PasswordInput(attrs = {
		'class': 'form-control input-lg',
		'placeholder': 'Enter your password here'
		}))
	repeat_password = forms.CharField(widget = forms.PasswordInput(attrs = {
		'class': 'form-control input-lg',
		'placeholder': 'Repeat your password here'
		}))
	avatar = forms.ImageField(required = False, widget = forms.FileInput(attrs = {
		'class': 'form-control input-lg',
		}))

	def clean_username(self):
		username = self.cleaned_data['username']
		if Profile.objects.exist_login(username):
			raise forms.ValidationError('Login is already exist!')
		return username

	def clean_repeat_password(self):
		data = self.cleaned_data
		if data['password'] != data['repeat_password']:
			raise forms.ValidationError('Different passwords!')
		return data['repeat_password']

	def clean_email(self):
		email = self.cleaned_data['email']
		if Profile.objects.exist_email(email):
			raise forms.ValidationError('Email is already exist!')
		return email

	def save(self):
		data = self.cleaned_data
		username = data['username']
		email = data['email']
		password = data['password']
		if self.cleaned_data['avatar'] is not None:
			profile = Profile.objects.create_user(username = username, email = email, \
				password = password, avatar = self.cleaned_data['avatar'])
		else:
			profile = Profile.objects.create_user(username = username, email = email, \
				password = password)


class SettingsForm(forms.Form):

	username = forms.CharField(widget = forms.TextInput(attrs = {
		'class': 'form-control input-lg',
		}))
	email = forms.EmailField(widget = forms.EmailInput(attrs = {
		'class': 'form-control input-lg',
		}))
	avatar = forms.ImageField(required = False, widget = forms.FileInput(attrs = {
		'class': 'form-control input-lg',
		}))

	def clean_username(self):
		username = self.cleaned_data['username']
		if self.fields['username'].has_changed(initial = self.initial['username'], \
			data = username):
			if Profile.objects.exist_login(username):
				raise forms.ValidationError('Login is already exist!')
		return username

	def clean_email(self):
		email = self.cleaned_data['email']
		if self.fields['email'].has_changed(initial = self.initial['email'], \
			data = email):
			if Profile.objects.exist_email(email):
				raise forms.ValidationError('Email is already exist!')
		return email

	def save(self, user):
		data = self.cleaned_data
		user.username = data['username']
		user.email = data['email']
		# user.save()
		if data['avatar'] is not None:
			user.avatar = data['avatar']
		# print(data['avatar'])
		user.save()


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'text', 'tags', ]

    def __init__(self, current_user, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['text'].widget.attrs.update({
            'class': 'form-control askme-textarea',
            'rows': 5,
        })
        self.fields['tags'].widget.attrs.update({
            'class': 'form-control'
        })
        self.current_user = current_user

    def save(self, commit=True):
        question = super(QuestionForm, self).save(commit=False)
        question.user = self.current_user
        if commit:
            question.save()
        return question.id

askMe_app/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.core.paginator import Paginator
from django.urls import reverse
from django.http import Http404
from django.http import JsonResponse

from django.contrib.auth import *

from .models import *
from .forms import *
from .documents import *

from elasticsearch_dsl.query import MultiMatch, Match

def paginate(objects_list, page_num, in_page = 5):
	
	paginator = Paginator(objects_list, in_page)
	try:
		page = paginator.page(page_num)
	except:
		page = paginator.page(paginator.num_pages)

	return page


def index(request, page_num = 1):

	questions = Question.objects.all()

	page = paginate(questions, page_num)

	if int(page_num) != int(page.number):
		return redirect('askMe_app:index', page.number)

	return render(request, 'askMe_app/index.html', {
			'page': page,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
		})

def hot(request, page_num = 1):

	questions = Question.objects.hot()

	page = paginate(questions, page_num)

	if int(page_num) != int(page.number):
		return redirect('askMe_app:hot', page.number)

	return render(request, 'askMe_app/hot.html', {
			'page': page,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
		})

def tag(request, tag_name, page_num = 1):

	questions = Question.objects.tag(tag_name)
	if questions.count() == 0:
		raise Http404()

	page = paginate(questions, page_num)

	if int(page_num) != int(page.number):
		return redirect('askMe_app:tag', tag_name, page.number)

	return render(request, 'askMe_app/tag.html', {
			'page': page,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
			'tag_name': tag_name,
		})

def question(request, question_id, page_num = 1):

	user = request.user

	question = get_object_or_404(Question, pk = question_id)
	answers = question.answer_set.all()	
	page = paginate(answers, page_num)

	if request.method == 'POST':
		form = AnswerForm(request.POST)
		if form.is_valid():
			form.save(question_id, user.id)
			return redirect('askMe_app:question', question_id, page.paginator.num_pages + 1)
	else:
		form = AnswerForm()

	if int(page_num) != int(page.number):
		return redirect('askMe_app:question', question_id, page.number)

	return render(request, 'askMe_app/question.html', {
			'form': form,
			'question': question,
			'page': page,
			'id': question_id,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
		})

def ask(request):

	user = request.user
	if not user.is_authenticated():
		next_url = reverse('askMe_app:ask')
		login_url = reverse('askMe_app:login')
		return redirect(login_url + '?next=' + next_url)

	if request.method == 'POST':
		form = AskForm(request.POST)
		if form.is_valid():
			question = form.save(user.id)
			return redirect('askMe_app:question', question.id)
	else:
		form = AskForm()

	return render(request, 'askMe_app/ask.html', {
			'form': form,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
		})

def login_view(request):

	user = request.user
	if user.is_authenticated():
		return redirect('askMe_app:index')

	next_page = request.GET.get('next')
	if next_page is None:
		next_page = 'askMe_app:index'

	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			login(request, form.user)
			return redirect(next_page)
	else:
		form = LoginForm()

	return render(request, 'askMe_app/login.html', {
			'form': form,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
		})

def logout_view(request):
	logout(request)
	next_page = request.GET.get('next')

	if next_page:
		return redirect(next_page)
	else:
		return redirect('askMe_app:index')

def signup(request):

	user = request.user

	if user.is_authenticated():
		return redirect('askMe_app:login')

	if request.method == 'POST':
		form = SignUpForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			user = authenticate(
				username = form.cleaned_data['username'],
				password = form.cleaned_data['password'] )
			auth.login(request, user)
			return redirect('askMe_app:login')
	else:
		form = SignUpForm()

	return render(request, 'askMe_app/signup.html', {
			'form': form,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
		})

def settings(request):

	user = request.user

	if not user.is_authenticated():
		return redirect('askMe_app:index')

	data = {'username': user.username, 'email': user.email}
	if request.method == 'POST':
		form = SettingsForm(request.POST, request.FILES, initial = data)
		if form.is_valid():
			form.save(user.profile)
	else:
		form = SettingsForm(initial = data)
		
	return render(request, 'askMe_app/settings.html', {
			'form': form,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
		})

def like_question(request):
	
	user = request.user

	if not user.is_authenticated():
		return JsonResponse({'status': 'error'})
	
	if request.method == "POST":
		question_id = request.POST.get('id', 0)
		like_type = bool(int(request.POST.get('type', 1)))

		try:
			question = Question.objects.get(pk = question_id)
		except:
			return JsonResponse({'status': 'error'})

		try:
			like = QuestionLike.objects.get(profile = user.profile, question = question)
			if like.like_type == like_type:
				like.delete()
			else:
				like.like_type = like_type
				like.save()
		except:
			like = QuestionLike(profile = user.profile, question = question, like_type = like_type)
			like.save()

		question.recalculate()
		return JsonResponse({'status': 'ok', 'likes': question.likes})

	return redirect('askMe_app:index')


def like_answer(request):

	user = request.user

	if not user.is_authenticated():
		return JsonResponse({'status': 'error'})
	
	if request.method == "POST":
		answer_id = request.POST.get('id', 0)
		like_type = bool(int(request.POST.get('type', 1)))

		try:
			answer = Answer.objects.get(pk = answer_id)
		except:
			return JsonResponse({'status': 'error'})

		try:
			like = AnswerLike.objects.get(profile = user.profile, answer = answer)
			if like.like_type == like_type:
				like.delete()
			else:
				like.like_type = like_type
				like.save()
		except:
			like = AnswerLike(profile = user.profile, answer = answer, like_type = like_type)
			like.save()

		answer.recalculate()
		return JsonResponse({'status': 'ok', 'likes': answer.likes})

	return redirect('askMe_app:index')


def correct_answer(request):

	user = request.user

	if request.method == "POST":
		answer_id = request.POST.get('id', 0)

		try:
			answer = Answer.objects.get(pk = answer_id)
		except:
			return JsonResponse({'status': 'error'})

		if user.profile == answer.question.author:
			answer.correct = not answer.correct
			answer.save()
			return JsonResponse({'status': 'ok', 'correct': answer.correct})
		else:
			return JsonResponse({'status': 'error'})

	return redirect('askMe_app:index')

def search(request, page_num = 1):
	query = request.GET.get('query')

	match = MultiMatch(query = query, fields=['title', 'text'])

	questions = QuestionDocument.search().query(match).to_queryset()

	page = paginate(questions, page_num)

	if int(page_num) != int(page.number):
		return redirect('askMe_app:search', page.number)

	return render(request, 'askMe_app/index.html', {
			'page': page,
			'members': Profile.objects.best(),
			'tags': Tag.objects.populars(),
			'search_value': query,
		})

askMe_app/templates/askMe_app/ask.html
{% extends "./base.html" %}

{% block content %}
<div class = "caption">
	New Question
</div>

<br>

<div class = "form">
	<form class = "form-horizontal" method = "POST">

		{% csrf_token %}
		
		{{ form.non_field_errors }}

		<div class = "form-group">
			<div class = "col-md-2">
				<label class = "control-label"> Title </label>
			</div>
			
			<div class = "col-md-8">
				{{ form.title }}
			</div>

			<div class = "col-md-2">
				{{ form.title.errors }}
			</div>
		</div>

		<div class = "form-group">
			<div class = "col-md-2">
				<label class = "control-label"> Text </label>
			</div>

			<div class = "col-md-8">
				{{ form.text }}
			</div>

			<div class = "col-md-2">
				{{ form.text.errors }}
			</div>
		</div>

		<div class = "form-group">
			<div class = "col-md-2">
				<label class = "control-label"> Tags </label>
			</div>

			<div class = "col-md-8">
				{{ form.tags }}
			</div>

			<div class = "col-md-2">
				{{ form.tags.errors }}
			</div>
		</div>

		<div class = "form-group">
			<div class = "col-md-offset-2 col-md-10">
				<button type = "submit" class = "btn btn-lg btn-default">
					<div class = "button-text"> Ask! </div>
				</button>
			</div>
		</div>
	</form>
</div>
{% endblock %}

askMe_app/templates/askMe_app/base.html
<!DOCTYPE html>

<html lang = "en">
	<head>
		<meta charset = "utf-8">
		<meta http-equiv = "X-UA-Compatible" content = "IE=edge">
		<meta name = "viewport" content = "width = device-width, initial-scale = 1">

		<meta name = "description" content = "">
		<meta name = "author" content = "">
		<link rel = "icon" href = "/favicon.ico">

		<title> AskMe </title>

		<link href = "/static/bootstrap/dist/css/bootstrap.css" rel = "stylesheet">
		<link href = "/static/bootstrap/dist/css/bootstrap-theme.css" rel = "stylesheet">

		<link href = "/static/styles.css" rel = "stylesheet">
	</head>

	<body>

		<div class = "header">
			<div class = "row">
				<div class = "col-md-3">
					<a href = "{% url 'askMe_app:index' %}">
						<button type = "button" class = "btn btn-default btn-lg">
							<div id = "name" class = "button-text"> AskMe </div> 
						</button>
					</a>
				</div>

				<div class = "col-md-5 align">
					<form role = "form" action="{% url 'askMe_app:search' %}">
						<div class="col-md-10">
							<input name = "query" type = "text" class = "form-control" placeholder = "Search" value = "{{ search_value }}">
						</div>
						<div class="col-md-2">
							<button type = "submit" class = "btn btn-default">
								<div class = "button-text"> Search </div>
							</button>
						</div>
					</form>
				</div>

				<div class = "col-md-1">
					<a href = "{% url 'askMe_app:ask' %}">
						<button type = "button" class = "btn btn-warning btn-lg">
							<div id = "name" class = "button-text"> Ask! </div> 
						</button>
					</a>
				</div>

				{% block user_panel %}

				{% if user.is_authenticated %}
					<div class = "col-md-1" id = "avatar">
						<img src = "{{ user.profile.avatar.url }}" class = "img-rounded">
					</div>

					<div class = "col-md-2 user-panel">
						<div class = "row">
							{{ user }}
						</div>
						<div class = "row">
							<a href = "{% url 'askMe_app:settings' %}"> settings </a>	
							&nbsp; &nbsp;  
							<a href = "{% url 'askMe_app:logout' %}?next={{ request.path }}"> log out </a>
						</div>
					</div>
				{% else %}
					<div class = "col-md-3 user-panel user-panel-lg">
						<a href = "{% url 'askMe_app:login' %}?next={{ request.path }}"> Log In </a>
						&nbsp; &nbsp;
						<a href = "{% url 'askMe_app:signup' %}"> Register </a>
					
						<img src = "" class = "hidden-img">
						
					</div>
				{% endif %}

				{% endblock %}

			</div>
		</div>

		<div class = "page">

			<div class = "row">

				<div class = "col-md-9 content">
					{% block content %} Content {% endblock %}
				</div>

				<div class = "col-md-3 sidebaar">
					<div class = "tags">
						<h1> Popular tags: </h1>
						
						{% for tag in tags %}
							<span class = "tag{% cycle 1 1 1 2 2 2 3 3 3 4 4 4 %}"> <a href = "{% url 'askMe_app:tag' tag.name %}"> {{ tag.name }} </a> </span> 
						{% endfor %}

					</div>

					<div class = "members">
						<h1> Best members: </h1>
							<h3>
								{% for m in members %}
								<div class = "col-md-7">
									{{ m.username }}: 
								</div>
								<div class = "col-md-5" align = "center">
									{{ m.publications }} <br>
								</div>
								{% endfor %}
							</h3>
					</div>
				</div>
			</div>

		</div>

		<div class = "floor">
			<div class = "row">
				<div class = "col-md-12">
					AskMe (c) TechnoPark 
					<br>
					2016
				</div>
			</div>
		</div>

		<script type = "text/javascript" src = "/static/js/jquery-3.1.1.js"> </script>
		<script type = "text/javascript" src = "/static/js/like.js"> </script>

	</body>
</html>

askMe_app/templates/askMe_app/base_loginned.html
{% extends "./base.html" %} 

{% block user_panel %}
<div class = "col-md-1" id = "avatar">
	<img src = "/avatar.jpg" class = "img-rounded">
</div>

<div class = "col-md-2 user-panel">
	<div class = "row">
		yaches
	</div>
	<div class = "row">
		<a href = "{% url 'askMe_app:settings' %}"> settings </a>	
		&nbsp; &nbsp;  
		<a href = "{% url 'askMe_app:login' %}"> log out </a>
	</div>
</div>
{% endblock %}

askMe_app/templates/askMe_app/hot.html
{% extends "./index.html" %}

{% block caption %}
<span class = "extra"> <a href = "{% url 'askMe_app:index' %}"> New Questions </a> </span>
<span> Hot Questions </span>
{% endblock %}

{% block paginator %}
	{% url "askMe_app:hot" as page_url %} 
	{% include "./paginator.html" %}
{% endblock %}

askMe_app/templates/askMe_app/index.html
{% extends "./base.html" %}

{% block content %}
	<div class = "caption">
		{% block caption %}
		<span> New Questions </span>
		<span class = "extra"> <a href = "{% url 'askMe_app:hot' %}"> Hot Questions </a> </span>
		{% endblock %}
	</div>

	{% csrf_token %}

	{% for question in page %}
	<div class = "message">
		<div class = "row">
			<div class = "col-md-2">
				<div class = "author">
					<img src = "{{ question.author.avatar.url }}" alt = "Avatar" class = "img-rounded img-thumbnail">
					<br>
					{{ question.author.username }}
					<br>
					<div class = "btn-group btn-group-sm">

						<button type = "button" class = "btn btn-default js-like-question" data-type = "0" data-id = "{{ question.id }}"> 
							<span class = "glyphicon glyphicon-arrow-down"> </span> 
						</button>
						
						<button type = "button" class = "btn btn-default disabled" id = "question-{{ question.id }}-likes"> {{ question.likes }} </button>
						
						<button type = "button" class = "btn btn-default js-like-question" data-type = "1" data-id = "{{ question.id }}"> 
							<span class = "glyphicon glyphicon-arrow-up"> </span> 
						</button>
					
					</div>
				</div>
			</div>
			<div class = "col-md-10">
				<div class = "caption">
					<a href = "{% url 'askMe_app:question' question.id %}"> 
						{{ question.title }}
					</a>
				</div>
				{{ question.text }} 
				<br>
				<a class = "number" href = "{% url 'askMe_app:question' question.id %}"> 
					<h4> Answer ({{ question.answers_amount }}) </h4> 
				</a> 
				<div class = "tags"> 
					Tags:
					{% for tag in question.tags.all %}
					<span>
						<a href = "{% url 'askMe_app:tag' tag %}"> {{ tag }}</a>
					</span>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>

	{% endfor %}

	{% block paginator %}
		{% url "askMe_app:index" as page_url %} 
		{% include "./paginator.html" %}
	{% endblock %}

{% endblock %}

askMe_app/templates/askMe_app/login.html
{% extends "./base.html" %}

{% block content %}
<div class = "login-form">
	<div class = "caption">
		Log In
	</div>

	<br>

	<div class = "form">

		<form class = "form-horizontal" method = "POST">

			{% csrf_token %}
			
			<div class = "form-group">
				<div class = "col-md-12">
					<span class = "danger">
						{{ form.non_field_errors }}
					</span>

				</div>
			</div>

			<div class = "form-group">
				<div class = "col-md-2">
					<label class = "control-label"> Login </label>
				</div>
				
				<div class = "col-md-7">
					<!-- <input required type = "text" maxlength = "48" class = "form-control input-lg" placeholder = "Enter your login here" id = "inputError1"> -->
					{{ form.username }}
				</div>

				<div class = "col-md-3">
					{{ form.username.errors }}
					<!-- <label class = "control-label">Input Error</label> -->
				</div>

			</div>

			<div class = "form-group">
				<div class = "col-md-2">
					<label class = "control-label"> Password </label>
				</div>
				
				<div class = "col-md-7">
					{{ form.password }}
					<!-- <input required type = "password" maxlength = "48" class = "form-control input-lg" placeholder = "Enter your password here" id = "inputError1"> -->
				</div>

				<div class = "col-md-3">
					<!-- <label class = "control-label">Input Error</label> -->
				</div>

			</div>

			<div class = "form-group">
				<div class = "col-md-offset-2 col-md-2">
					<button type = "submit" class = "btn btn-lg btn-default">
						<div class = "button-text"> Log In! </div>
					</button>
				</div>

				<div class = "col-md-5" id = "new-account">
					<a href = "{% url 'askMe_app:signup' %}">
						<button type = "button" class = "btn btn-lg btn-default">
							<div class = "button-text"> Create new account </div>
						</button>
					</a>
				</div>
			</div>

		</form>
	</div>	
</div>
{% endblock %}

askMe_app/templates/askMe_app/tag.html
{% extends "./index.html" %}

{% block caption %}
<span> Tag: {{ tag_name }} </span>
{% endblock %}

{% block paginator %}
	{% url "askMe_app:tag" tag_name as page_url %} 
	{% include "./paginator.html" %}
{% endblock %}